### ISSUE TITLE
member-counter

### ISSUE THREAD

**Issue by zevnda** [ProbablyRaging/CreatorBot#3]
Is null if no one has a status other than offline

#2 
```
C:\Users\proba\Desktop\CreatorBot2.0\modules\member-counter.js:9
            let totalOnline = fetchedMembers.filter(member => member.presence.status !== 'offline').size + 130;
                                                                              ^

TypeError: Cannot read properties of null (reading 'status')
    at C:\Users\proba\Desktop\CreatorBot2.0\modules\member-counter.js:9:79
    at Map.filter (C:\Users\proba\Desktop\CreatorBot2.0\node_modules\@discordjs\collection\dist\index.js:1:2066)
    at C:\Users\proba\Desktop\CreatorBot2.0\modules\member-counter.js:9:46
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by zevnda** [comment]
Should be fixed in 257bb48

Edit: revised again in 6fc693f
